### ISSUE TITLE
zivid.Frame() Function and versioning

### ISSUE THREAD

**Issue by YunongPan** [zivid/zivid-python-samples#133]
Hi,

I want to use the "zivid.Frame(path_dir).point_cloud()" Function but I always get the error "RuntimeError: Failed to load .zdf file. To load this file you may need to update to a newer version of Zivid SDK.".

I am working on Ubuntu 18.04

Initially I had the 2.6.1 SDK and 2.4.0.2.6.0. zivid version. Then I upgraded the zivid version to 2.5.0.2.6.1. (python 3.7.3) which didn't help.
Then i downgraded zivid back to 2.4.0.2.6.0 (python 3.6) and downgraded the SDK to 2.6.0 which also didn't help.

Thank you!

**Comment by SatjaSivcev** [comment]
Hi,

Since you have closed the issue I suppose you have resolved it?

**Comment by christinaionescu** [comment]
Hi :) I accidentally posted from the wrong account, sorry about that. I reposted it here: https://github.com/zivid/zivid-python/issues/166 as I think it is a more general question.
