### ISSUE TITLE
Upgrade CI python version to 3.8

### ISSUE THREAD

**Issue by trym-b** [zivid/zivid-python-samples#50]
Unless the targeted python version is exactly the default python version for `ubuntu 18.04`. If we are targeting a specific python version it should be made explicit.

**Comment by knatten** [comment]
I think we should rather use 3.5, which is the minimum required version for [zivid-python](https://github.com/zivid/zivid-python). We need to be sure that the samples are compatible with the same version as zivid-python.

Ideally, use a matrix like in their [azure-pipelines.yml](https://github.com/zivid/zivid-python/blob/master/azure-pipelines.yml), and test on several versions.

**Comment by SatjaSivcev** [comment]
I am planning to modify CI so to use U16 U18 and U20 for setup.sh test and U18 for lint.sh test. I suggest we then use whatever python versions are the default for Ubuntu installations? That would be 3.5 for U16, 3.6 for U18 and 3.8 for U20. What do you think?

**Comment by trym-b** [comment]
Sounds good, but just to make it clear that means we will require at minmum python 3.5 to run the samples.
Python 3.6 and 3.8 should be able to run 3.5 code just fine.

Also, I would recommend running the linter on ubuntu 20.04 instead of 18.04 if you are updating the linters as well.

**Comment by nedrebo** [comment]
This is what we do in the official wrapper:

* https://github.com/zivid/zivid-python#test-matrix
* https://github.com/zivid/zivid-python/blob/master/.github/workflows/main.yml#L14

The main goal is to have one dimension per minor Python version per Win/Linux. Then we assume that the patch version of Python does not matter.

**Comment by nedrebo** [comment]
As you can see we are missing 3.9 on Linux, but that is tracked by https://github.com/zivid/zivid-python/issues/107.

**Comment by SatjaSivcev** [comment]
> 
> 
> Sounds good, but just to make it clear that means we will require at minmum python 3.5 to run the samples.
> Python 3.6 and 3.8 should be able to run 3.5 code just fine.
> 
> Also, I would recommend running the linter on ubuntu 20.04 instead of 18.04 if you are updating the linters as well.

Updating linter to 20.04 (3.8) is blocked by https://github.com/zivid/zivid-python-samples/issues/95
